version: "3.9"

services:
  owlchirp:
    image: override_this
    environment:
      AWS_DEFAULT_REGION: replaced_value
      CONNECT_INSTANCE: replaced_value
      DB_STRING: replaced_value
    volumes:
      - owlchirp:/data
    networks:
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        caddy: replaced_value
        caddy.reverse_proxy: "{{ upstreams 8080 }}"

volumes:
  owlchirp:

networks:
  public:
    external: true