version: "3.9"

services:
  owlchirp:
    image: ${IMAGE}
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      CONNECT_INSTANCE: ${CONNECT_INSTANCE}
      DB_STRING: ${DB_STRING}
    volumes:
      - owlchirp:/data
    networks:
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        caddy: ${HOST}
        caddy.reverse_proxy: "{{ upstreams 8080 }}"

volumes:
  owlchirp:

networks:
  public:
    external: true