name: Build / Push AWS ECR; Deploy to EC2

on:
  push:
    branches:
    - production

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id:   aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_DEFAULT_REGION }}

      - name: Variables
        id:   v
        run: |
          echo "::set-output name=date::$(date '+%m_%d_%Y')"
          echo "::set-output name=reponame::$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')"

      - name: Login to Amazon ECR
        id:   login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.v.outputs.reponame }}
          CONNECT_INSTANCE: ${{ vars.CONNECT_INSTANCE }}
          TIME_ZONE: ${{ vars.TIME_ZONE }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.v.outputs.date }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:build_${{ github.run_number }}
          build-args: |
            SET_GIT_SHA=${{ github.sha }}
            SET_BUILD_NUMBER=${{ github.run_number }}
            CONNECT_INSTANCE=${{ env.CONNECT_INSTANCE }}
            TIME_ZONE=${{ env.TIME_ZONE }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max

      # Configure deployment package to use AWS repo with image of today's date.
      - name: Update stack to repo
        env:
          AWS_DEFAULT_REGION:  ${{ vars.AWS_DEFAULT_REGION }}
          CONNECT_INSTANCE: ${{ vars.CONNECT_INSTANCE }}
          DB_STRING: ${{ vars.DB_STRING }}
          ECR_REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.v.outputs.reponame }}
          HOST: ${{ vars.HOST }}
        run: |
          sed -i "s;image:.*;image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.v.outputs.date }};" deploy/docker-compose.yml
          sed -i "s;caddy:.*;caddy: ${{ env.HOST }};" deploy/docker-compose.yml
          sed -i "s;AWS_DEFAULT_REGION:.*;AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }};" deploy/docker-compose.yml
          sed -i "s;DB_STRING:.*;DB_STRING: ${{ env.DB_STRING }};" deploy/docker-compose.yml
          sed -i "s;CONNECT_INSTANCE:.*;CONNECT_INSTANCE: ${{ env.CONNECT_INSTANCE }};" deploy/docker-compose.yml

      - name: Deploy
        env:
          SSH_STRING: ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOSTNAME }}
          DOCKER_HOST: ssh://${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOSTNAME }}
          REGION: ${{ vars.AWS_DEFAULT_REGION }}
          ECR_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REMOTE_SERVER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo -e "Host *\n  StrictHostKeyChecking no" > ~/.ssh/config
          docker stack deploy --with-registry-auth -c deploy/docker-compose.yml ${{ steps.v.outputs.reponame }}
          
